# Bash skips all the default ruby setup
language: bash

dist: trusty
sudo: false

before_install:
- node --version

# We use a subshell here since 'cd' persists to subsequent commands otherwise.
# See https://docs.travis-ci.com/user/common-build-problems/#SSH-is-not-working-as-expected
install:
- bash -c 'cd tools && npm install'

script:
- make build
- make lint
