manifest:
  major_version: 3
  minor_version: 7
  build_version: 0
  revision_version: 0
component_library_manifest:
  major_version: 3
  minor_version: 7
  build_version: 0
  revision_version: 0
starter_library_manifest:
  major_version: 3
  minor_version: 7
  build_version: 0
  revision_version: 0
one_trust_library_manifest:
  major_version: 202405
  minor_version: 1
  build_version: 0
fox_video_player_library_manifest:
  major_version: 1
  minor_version: 45
  build_version: 0
