manifest:
  major_version: 3
  minor_version: 0
  build_version: 0
  revision_version: 0
component_library_manifest:
  major_version: 3
  minor_version: 0
  build_version: 0
  revision_version: 0
starter_library_manifest:
  major_version: 3
  minor_version: 0
  build_version: 0
  revision_version: 0
