settings:
  # Settings are added to constants.settings via getSettings
  # Any constants that need to be templatized via handlebars should be added via settings
  mode: "production"
  version: "{{versionUnderscored}}"
  contentType: "hls"
  shortAppName: "tubitv"
  platformName: "roku"
  starterComponentsUrl: "https://cdn.adrise.tv/hotpatches/roku/starter-components/tubi_starter_components_{{versionMinorUnderscored}}.pkg"
  remoteComponentsUrl: "https://cdn.adrise.tv/hotpatches/roku/components/tubi_remote_components_{{versionUnderscored}}.pkg"
  remoteComponentsExtension: "pkg"
  migrateToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjo0LCJwbGF0Zm9ybSI6InJva3UiLCJpYXQiOjE0NTgzMjkzNDd9.726iJo5B68VLn-HfWj4V5mwrn6vI5MQOfsQcs-gT5TA"
  suitest: false
  noAds: false
  charlesProxyEnabled: false
  charlesProxyUrl: ""

manifest:
  title: "Tubi"
  mm_icon_focus_hd: "pkg:/locale/images/channel-icon-hd-290x218.png"
  mm_icon_focus_sd: "pkg:/locale/images/channel-icon-sd-246x140.png"
  splash_screen_fhd: "pkg:/images/splash-fhd.jpg"
  splash_screen_hd: "pkg:/images/splash-hd.jpg"
  splash_screen_sd: "pkg:/images/splash-sd.jpg"
  bs_libs_required: roku_ads_lib
  # We have a workaround for 9-patch handling when ui_resolutions is "fhd" and scaling down for non-4k devices. 
  # If we ever add "sd" or "hd", the workaround will also need to be removed.
  ui_resolutions: "fhd"
  uri_resolution_autosub: "$$RES$$,sd,hd,fhd"
  requires_widevine_drm: 1
  requires_widevine_version: "1.0"
  supports_input_launch: 1 
  supports_etc_seek: 1 
  supports_etc_next: 1 
  splash_min_time: 2000
  splash_rsg_optimization: 1
  rsg_version: 1.2
  confirm_partner_button: 1
  sdk_instant_resume: 1
  run_as_process: 1

component_library_manifest:
  title: "Tubi Component Library"
  subtitle: "Remote loading for scenegraph components"
  sg_component_libs_provided: "TubiRemoteLibrary"
  bs_libs_required: roku_ads_lib
  requires_widevine_drm: 1
  requires_widevine_version: "1.0"
  hidden: 1
  rsg_version: 1.2
  confirm_partner_button: 1

starter_library_manifest:
  title: "Tubi Starter Library"
  subtitle: "Startup components"
  sg_component_libs_provided: "TubiStarterLibrary"
  hidden: 1
  rsg_version: 1.2
  confirm_partner_button: 1
