settings:
  mode: "production"
  contentType: "hls"
  shortAppName: "tubitv"
  platformName: "roku"
  GridStyle: "Flat-Movie"
  SetPosterStyle: "rounded-rect-16x9-generic"
  adLoadingBackgroundColor: "#222223"
  adLoadingFontColor: "#EBEBEB"
  loadingImageUrl: "pkg://images/tubi-ad-loading-336x201.png"
  registerWithTubi: true
  hotPatchUrl: "http://cdn.adrise.com/hotpatches/roku/11.brs"
  appName: "Tubi TV"
  isLiveTVOn: true
  isRokuAdFrameworkOn: false
  migrateToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjo0LCJwbGF0Zm9ybSI6InJva3UiLCJpYXQiOjE0NTgzMjkzNDd9.726iJo5B68VLn-HfWj4V5mwrn6vI5MQOfsQcs-gT5TA"

manifest:
  title: "Tubi TV"
  subtitle: "What TV was meant to be"
  mm_icon_focus_hd: "pkg:/images/FREETVMOVIES_Tubi_icon_336x201.jpg"
  mm_icon_side_hd: "pkg:/images/FREETVMOVIES_Tubi_icon_108x69.jpg"
  mm_icon_focus_sd: "pkg:/images/FREETVMOVIES_Tubi_icon_248x140.jpg"
  mm_icon_side_sd: "pkg:/images/FREETVMOVIES_Tubi_icon_80x46.jpg"
  splash_screen_hd: "pkg:/images/FREETVMOVIES_Tubi_icon_1280x720.jpg"
  splash_screen_sd: "pkg:/images/FREETVMOVIES_Tubi_icon_720x480.jpg"
  major_version: 2
  minor_version: 0
  build_version: 3
  bs_libs_required: roku_ads_lib
  ui_resolutions: "fhd"
  rsg_version: 1.0

theme:
  ThemeType: "flat-movie"
  BackgroundColor: "#222223"
  GridScreenBackgroundColor: "#222223"
  BannerBackgroundColor: "none"
  GridScreenMessageColor: "#FFFFFF"
  GridScreenDescriptionTitleColor: "#ff9900"
  GridScreenDescriptionDateColor: "#666666"
  GridScreenDescriptionRuntimeColor: "#666666"
  GridScreenDescriptionSynopsisColor: "#929292"
  GridScreenRetrievingColor: "#cccccc"
  GridScreenListNameColor: "#cccccc"
  CounterTextLeft: "#FFFFFF"
  CounterSeparator: "#FFFFFF"
  ButtonMenuNormalText: "#888888"
  ButtonMenuHighlightText: "#ff8800"
  CounterTextRight: "#FFFFFF"
  SpringboardTitleText: "#AAAAAA"
  SpringboardSynopsisColor: "#AAAAAA"
  SpringboardDirectorColor: "#666666"
  SpringboardDirectorLabelColor: "#888888"
  SpringboardActorColor: "#666666"
  SpringboardGenreColor: "#666666"
  SpringboardRuntimeColor: "#888888"
  BreadcrumbTextLeft: "#cccccc"
  PosterScreenLine1Text: "#888888"
  PosterScreenLine2Text: "#CCCCCC"
  BreadcrumbTextRight: "#cccccc"
  GridScreenLogoOffsetHD_X: "0"
  GridScreenLogoOffsetHD_Y: "0"
  GridScreenLogoOffsetSD_X: "0"
  GridScreenLogoOffsetSD_Y: "0"
  GridScreenBorderOffsetHD: "(-10,-11)"
  GridScreenBorderOffsetSD: "(-23,-20)"
  GridScreenDescriptionOffsetHD: "(200,258)"
  GridScreenDescriptionOffsetSD: "(102,145)"
  OverhangOffsetSD_X: "0"
  OverhangOffsetSD_Y: "0"
  OverhangOffsetHD_X: "0"
  OverhangOffsetHD_Y: "0"
  OverhangPrimaryLogoOffsetHD_X: "0"
  OverhangPrimaryLogoOffsetHD_Y: "0"
  GridScreenLogoHD: "pkg:/images/TubiTV_GridscreenLogo_HD_1280x65.jpg"
  GridScreenLogoSD: "pkg:/images/TubiTV_GridscreenLogo_SD_720x45.jpg"
  TallBannerHD: "pkg:/images/TubiTV_TallBanner_HD_1280x135.jpg"
  TallBannerSD: "pkg:/images/TubiTV_TallBanner_SD_720x125.jpg"
  GridScreenFocusBorderHD: "pkg:/images/frame-glow-hd3.png"
  GridScreenFocusBorderSD: "pkg:/images/frame-glow-sd3.png"
  GridScreenDescriptionImageHD: "pkg:/images/bubble-hd.png"
  GridScreenDescriptionImageSD: "pkg:/images/bubble-sd.png"
  GridScreenOverhangHeightHD: "65"
  GridScreenOverhangHeightSD: "45"
  OverhangLogoHD: "pkg:/images/TubiTV_TallBanner_HD_1280x135.jpg"
  OverhangLogoSD: "pkg:/images/TubiTV_TallBanner_SD_720x125.jpg"


