settings:
  mode: "production"
  version: "{{versionUnderscored}}"
  contentType: "hls"
  shortAppName: "tubitv"
  platformName: "roku"
  adLoadingBackgroundColor: "#222223"
  adLoadingFontColor: "#EBEBEB"
  loadingImageUrl: "pkg://images/tubi-ad-loading-336x201.png"
  hotPatchUrl: "http://cdn.adrise.com/hotpatches/roku/{{versionMinorDotted}}.brs"
  remoteComponentsHost: "http://cdn.adrise.com/hotpatches/roku/components"
  remoteComponentsExtension: "pkg"
  migrateToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjo0LCJwbGF0Zm9ybSI6InJva3UiLCJpYXQiOjE0NTgzMjkzNDd9.726iJo5B68VLn-HfWj4V5mwrn6vI5MQOfsQcs-gT5TA"
  allowAfterHours: true

manifest:
  title: "Tubi"
  subtitle: "What TV was meant to be"
  mm_icon_focus_hd: "pkg:/images/channel-icon-hd-540x405.png"
  splash_screen_fhd: "pkg:/images/splash-fhd.png"
  bs_libs_required: roku_ads_lib
  # We have a workaround for 9-patch handling when ui_resolutions is "fhd" and scaling down for non-4k devices. 
  # If we ever add "sd" or "hd", the workaround will also need to be removed.
  ui_resolutions: "fhd"
  uri_resolution_autosub: "$$RES$$,sd,hd,fhd"

component_library_manifest:
  title: "Tubi Component Library"
  subtitle: "Remote loading for scenegraph components"
  sg_component_libs_provided: "TubiRemoteLibrary"
  bs_libs_required: roku_ads_lib
  hidden: 1
