settings:
  # Settings are added to constants.settings via getSettings
  # Any constants that need to be templatized should be added via settings
  mode: "production"

  foxVideoPlayerComponentsUrl:  "https://mrcdn-production.tubitv.com/appFiles/fox-video-player-components/fox_video_player_{{foxVideoPlayerVersionUnderscored}}.pkg"
