settings:
  # Settings are added to constants.settings via getSettings
  # Any constants that need to be templatized should be added via settings
  mode: "qa"
  noAds: false  #setting to true will prevent ads from being requested from rainmaker
  stagingApis: false  #setting to true will use UAPI staging APIs (matrix, cms, user_device)
  remoteComponentsExtension: "zip" #prevents packages being built for qa builds, as they are not used - makes for faster builds
  skipAgeGate: false #setting to true will prevent the COPPA age gate screen from appearing

  # setting to true will activate/signup the app automatically with a generated email and username
  # (if the values of suitest & stagingApis are also true)
  automaticActivation: true

  #number of seconds that age information will be stored on the device.
  #Set to 0 to see age gate every time the app is opened.
  #Also controls instant resume timeout for signed out users
  coppaHasAgeDuration: 60

  # enabling showOnBoardingAlways will show OnBoarding Screen every time the app is launched as non-production mode for guest users.
  # This field is added for testing purpose
  showOnBoardingAlways: false

  # email/password values will be used to automatically sign a user in when "sign in" is selected
  email: ""
  password: ""

  # setting printReqAndResInfo as true will print log for all api request information
  printReqAndResInfo: true

  #To enable the Charles Proxy, set CharlesProxyEnabled true
  charlesProxyUrl: "http://{{localHostAddress}}:8888"
  charlesProxyEnabled: false

  bs_const:
    #By default nothing will be printed to debug console.(port : 8085 )
    #To enable console debuglogs, set consoleLoggingEnabled to true
    consoleLoggingEnabled: true

  #setting to true will result in suitest being loaded
  suitest: false

  #setting to true will use analytics proxy server and display category slugs and content id in UI
  suitestjs: false

manifest:
  # Set to 0 to prevent instant resume functionality.
  # Setting to 0 is required to run analytics automated tests via Suitest's v3 js library
  run_as_process: 1
