settings:
  # Settings are added to constants.settings via getSettings
  # Any constants that need to be templatized should be added via settings
  mode: "qa"
  noAds: false  #setting to true will prevent ads from being requested from rainmaker
  stagingApis: false  #setting to true will use UAPI staging APIs (matrix, cms, user_device)
  remoteComponentsExtension: "zip" #prevents packages being built for qa builds, as they are not used - makes for faster builds
  skipAgeGate: false #setting to true will prevent the COPPA age gate screen from appearing

  # setting to true will activate/signup the app automatically with a generated email and username
  # (if the values of suitest & stagingApis are also true)
  automaticActivation: true

  #number of seconds that age information will be stored on the device.
  #Set to 0 to see age gate every time the app is opened.
  #Also controls instant resume timeout for signed out users
  coppaHasAgeDuration: 60

  #time in seconds after which the linear video player goes fullscreen.
  linearFullscreenTimeout: 10

  #the number of seconds before the video overlay autohides in Live TV after last button pressed.
  videoOverlayAutoHideTime: 5


  # enabling showOnBoardingAlways will show OnBoarding Screen every time the app is launched as non-production mode for guest users.
  # This field is added for testing purpose
  showOnBoardingAlways: false

 # enabling showFIFAIntroModalAlways will show FIFA Intro modal every time the app is launched as non-production mode for guest users.
  # This field is added for testing purpose
  showFIFAIntroModalAlways: false

  # enabling showRegistrationModalForNewUser will show registration Intro modal every time the app is launched as non-production mode for new users.
  # This field is added for testing purpose Only
  showRegistrationModalForNewUser: false


  # disabling hideStartupModals will let other showmodal flags to work as set. For example,
  # if hideStartupModals=false and showRegistrationModalForNewUser=true ===> registration modal will be shown for new user
  # if hideStartupModals=false and showFIFAIntroModalAlways=true ====> FIFA modal will be shown
  # if hideStartupModals=true ==> no startup modals are shown irrespective off individual state
  hideStartupModals: true



  #FIFA worldcup tournament start date/end date for testing purposes. Please follow the format
  tournamentStartDate: "2022-11-20T00:00:00Z"
  tournamentEndDate: "2022-12-18T00:00:00Z"

  # A date which will be used as the current date within the app. Use this to simulate a date in the past or future. If a date is provided this gets converted to a time offset in seconds to allow testing of features only available at a particular time
  # testingTimeOffset: "2023-02-12T20:00:00Z"

  # email/password values will be used to automatically sign a user in when "sign in" is selected
  email: ""
  password: ""

  # setting printReqAndResInfo as true will print log for all api request information
  printReqAndResInfo: true

  #To enable the Charles Proxy, set CharlesProxyEnabled true
  charlesProxyUrl: "http://{{localHostAddress}}:8888"
  charlesProxyEnabled: false

  # Setting the below value to true will enable youbora tracking.
  youboraEnabled: false
  # Setting the below value to true will enable youbora request logging into the console.
  youboraDebugEnabled: false

  useStarterComponents: false
  useRemoteComponents: false

  # A date which will be used as the current date within the app. Use this to simulate a date in the past or future. If a date is provided this gets converted to a time offset in seconds to allow testing of features only available at a particular time
  # testingTimeOffset: "2022-12-18T20:00:00Z"

  # Overrides the system level screenscaver timeout with this value (in seconds)
  # overrideScreensaverTimeout: 10

  bs_const:
    #By default nothing will be printed to debug console.(port : 8085)
    #To enable console debug logs, set consoleLoggingEnabled to true
    consoleLoggingEnabled: true
    #setting to true will use analytics proxy server and display category slugs and content id in UI
    suitestjs: false
    # Setting to true will route linear playback manifest request through qa proxy.
    linearQaProxyEnabled: false

  #setting to true will result in suitest being loaded
  suitest: false

manifest:
  # Set to 0 to prevent instant resume functionality.
  # Setting to 0 is required to run analytics automated tests via Suitest's v3 js library
  run_as_process: 1
