# Set up a staging environment
settings:
  # Settings are added to constants.settings via getSettings
  # Any constants that need to be templatized should be added via settings
  mode: "staging"
  starterComponentsUrl: "https://rcdn-staging.tubitv.com/appFiles/starter-components/tubi_starter_components_{{versionMinorUnderscored}}.pkg"
  remoteComponentsUrl: "https://rcdn-staging.tubitv.com/appFiles/components/tubi_remote_components_{{versionUnderscored}}.pkg"
  oneTrustComponentsUrl: "https://rcdn-staging.tubitv.com/appFiles/one-trust-components/tubi_one_trust_components_{{oneTrustVersionUnderscored}}.pkg"
  foxVideoPlayerComponentsUrl: "https://rcdn-staging.tubitv.com/appFiles/fox-video-player-components/fox_video_player_{{foxVideoPlayerVersionUnderscored}}.pkg"
