# Set up a staging environment
settings:
  # Settings are added to constants.settings via getSettings
  # Any constants that need to be templatized should be added via settings
  mode: "staging"
  starterComponentsUrl: "https://s3-us-west-1.amazonaws.com/adrise-bryan-playground/roku-staging/starter-components/tubi_starter_components_{{versionMinorUnderscored}}.pkg"
  remoteComponentsUrl: "https://s3-us-west-1.amazonaws.com/adrise-bryan-playground/roku-staging/components/tubi_remote_components_{{versionUnderscored}}.pkg"
   rcdnStarterComponentsUrl: "https://rcdn-staging.tubitv.com/appFiles/starter-components/tubi_starter_components_{{versionMinorUnderscored}}.pkg"
  rcdnRemoteComponentsUrl:  "https://rcdn-staging.tubitv.com/appFiles/components/tubi_remote_component_{{versionUnderscored}}.pkg"