
' This file is automatically generated by the gulp task generateLocalClientErrorConfigFileContents and should not be manually updated
Function getLocalClientErrorConfig()
  return {
  "conditions": {
    "user_not_found": {
      "response_code": "user_not_found",
      "retry": false
    },
    "expired_token": {
      "response_code": "expired_token",
      "retry": true,
      "retry_strategy": "exp_backoff_with_new_token",
      "max_retries": 1
    },
    "retry_after": {
      "header": "Retry-After",
      "retry": true
    }
  },
  "default": {
    "400": {
      "retry": false
    },
    "401": {
      "retry": true,
      "retry_strategy": "exp_backoff_with_new_token",
      "max_retries": 1,
      "conditions": [
        "user_not_found"
      ]
    },
    "403": {
      "retry": false,
      "conditions": [
        "expired_token"
      ]
    },
    "404": {
      "retry": false
    },
    "422": {
      "retry": false
    },
    "429": {
      "retry": false,
      "conditions": [
        "retry_after"
      ]
    },
    "451": {
      "retry": false
    },
    "500": {
      "retry": true,
      "retry_strategy": "exp_backoff",
      "max_retries": 3
    },
    "501": {
      "retry": false,
      "conditions": [
        "retry_after"
      ]
    },
    "502": {
      "retry": false,
      "conditions": [
        "retry_after"
      ]
    },
    "503": {
      "retry": false,
      "conditions": [
        "retry_after"
      ]
    },
    "timeout_seconds": 8
  },
  "services": {
    "account": {
      "routes": {
        "/user_device/login/refresh": {
          "POST": {
            "status_codes": {
              "403": {
                "retry": false
              }
            }
          }
        },
        "/user_device/login/transfer": {
          "POST": {
            "status_codes": {
              "403": {
                "retry": false
              }
            }
          }
        },
        "/user_device/logout": {
          "POST": {
            "status_codes": {
              "403": {
                "retry": false
              },
              "500": {
                "retry": false
              }
            }
          }
        },
        "/device/anonymous/signing_key": {
          "POST": {
            "status_codes": {
              "403": {
                "retry": false
              }
            }
          }
        },
        "/device/anonymous/refresh": {
          "POST": {
            "status_codes": {
              "403": {
                "retry": false
              }
            }
          }
        },
        "/device/anonymous/token": {
          "POST": {
            "status_codes": {
              "403": {
                "retry": false
              }
            }
          }
        }
      }
    },
    "datascience": {
      "routes": {
        "/datascience/logging": {
          "POST": {
            "timeout_seconds": 5,
            "status_codes": {
              "403": {
                "retry": false
              },
              "500": {
                "retry": false
              }
            }
          }
        }
      }
    },
    "analytics": {
      "routes": {
        "/analytics-ingestion/v2/single-event": {
          "POST": {
            "timeout_seconds": 5,
            "status_codes": {
              "403": {
                "retry": false
              },
              "500": {
                "retry": false
              }
            }
          }
        }
      }
    },
    "tensor": {
      "timeout_seconds": 10
    },
    "content": {
      "timeout_seconds": 10
    },
    "lishi": {
      "timeout_seconds": 10,
      "routes": {
        "/api/v2/view_history": {
          "POST": {
            "status_codes": {
              "500": {
                "retry": false
              }
            }
          }
        }
      }
    },
    "user_queue": {
      "timeout_seconds": 10
    },
    "license": {
      "timeout_seconds": 10,
      "routes": {
        "/challenge": {
          "POST": {
            "status_codes": {
              "500": {
                "retry": false
              }
            }
          }
        }
      }
    },
    "popper": {
      "timeout_seconds": 10
    },
    "config_hub": {
      "timeout_seconds": 10
    },
    "rainmaker": {
      "timeout_seconds": 600
    },
    "autopilot": {
      "timeout_seconds": 5
    },
    "search": {
      "timeout_seconds": 5
    },
    "crm": {
      "timeout_seconds": 5
    },
    "srt": {
      "timeout_seconds": 10
    }
  }
}
End Function