
    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    

    '***************************************************
    'Function maps
    '***************************************************
    function RBSFM_getFunctionsForFile(filename)
  map = {
    "Test_VideoPlayer_Cuepoints":RBSFM_getFunctions_Test_VideoPlayer_Cuepoints 
    "Test_VideoPlayer_VideoErrorHelpers":RBSFM_getFunctions_Test_VideoPlayer_VideoErrorHelpers 
    "Test_VideoPlayer_VideoPlayerHelpers":RBSFM_getFunctions_Test_VideoPlayer_VideoPlayerHelpers 
    "Test_ChannelDetailScreen_Helpers":RBSFM_getFunctions_Test_ChannelDetailScreen_Helpers 
    "component_SpritePoster":RBSFM_getFunctions_component_SpritePoster 
    "componentTest_CategoryGridList":RBSFM_getFunctions_componentTest_CategoryGridList 
    "componentTest_ChannelDetailScreen":RBSFM_getFunctions_componentTest_ChannelDetailScreen 
    "componentTest_DetailScreen":RBSFM_getFunctions_componentTest_DetailScreen 
    "componentTest_InfoPanel":RBSFM_getFunctions_componentTest_InfoPanel 
    "componentTest_SettingsScreen":RBSFM_getFunctions_componentTest_SettingsScreen 
    "componentTest_TubiProgressBar":RBSFM_getFunctions_componentTest_TubiProgressBar 
    "componentTest_VideoPlayer":RBSFM_getFunctions_componentTest_VideoPlayer 
    "test_CmsApi":RBSFM_getFunctions_test_CmsApi 
    "StringUtilsUnitTests":RBSFM_getFunctions_StringUtilsUnitTests 
    "test_Request":RBSFM_getFunctions_test_Request 
    "test_RequestQueue":RBSFM_getFunctions_test_RequestQueue 
    "test_Sentry":RBSFM_getFunctions_test_Sentry 
    "test_StringUtils":RBSFM_getFunctions_test_StringUtils 
    "test_TubiAds":RBSFM_getFunctions_test_TubiAds 
    "test_TubiAuth":RBSFM_getFunctions_test_TubiAuth 
    "test_TubiBookmarks":RBSFM_getFunctions_test_TubiBookmarks 
    "test_TubiExperiments":RBSFM_getFunctions_test_TubiExperiments 
    "test_TubiExternalConfig":RBSFM_getFunctions_test_TubiExternalConfig 
    "test_TubiLogger":RBSFM_getFunctions_test_TubiLogger 
    "test_tubimetadatatranslate":RBSFM_getFunctions_test_tubimetadatatranslate 
    "test_TubiNodeHelpers":RBSFM_getFunctions_test_TubiNodeHelpers 
    "test_TubiTracking":RBSFM_getFunctions_test_TubiTracking 
    "test_Settings":RBSFM_getFunctions_test_Settings 
  } 
  return map[filename]
end function

function RBSFM_getFunctions_Test_VideoPlayer_Cuepoints()
  return {
    "TestSuite_VideoPlayer_Cuepoints":TestSuite_VideoPlayer_Cuepoints 
    "testCase_isInWindow":testCase_isInWindow 
    "testCase_isAtPosition":testCase_isAtPosition 
  } 

end function

function RBSFM_getFunctions_Test_VideoPlayer_VideoErrorHelpers()
  return {
    "TestSuite_VideoPlayer_VideoErrorHelpers":TestSuite_VideoPlayer_VideoErrorHelpers 
    "VideoErrorHelpers_SetUp":VideoErrorHelpers_SetUp 
    "TestCase_getPlaybackErrorInfo":TestCase_getPlaybackErrorInfo 
    "TestCase_getPlaybackErrorInfo_Position0":TestCase_getPlaybackErrorInfo_Position0 
    "TestCase_getPlaybackErrorInfo_Error3":TestCase_getPlaybackErrorInfo_Error3 
    "TestCase_getPlaybackErrorInfo_Error3_Position0":TestCase_getPlaybackErrorInfo_Error3_Position0 
    "TestCase_removeExcessUrl":TestCase_removeExcessUrl 
  } 

end function

function RBSFM_getFunctions_Test_VideoPlayer_VideoPlayerHelpers()
  return {
    "TestSuite_VideoPlayer_VideoPlayerHelpers":TestSuite_VideoPlayer_VideoPlayerHelpers 
    "TestMock__VideoPlayerHelpers_MockVideoNode":TestMock__VideoPlayerHelpers_MockVideoNode 
    "TestCase_isActiveVideoState":TestCase_isActiveVideoState 
    "TestCase_isButtonPressAllowed":TestCase_isButtonPressAllowed 
  } 

end function

function RBSFM_getFunctions_Test_ChannelDetailScreen_Helpers()
  return {
    "TestSuite_ChannelDetailScreen_Helpers":TestSuite_ChannelDetailScreen_Helpers 
    "ChannelDetailScreenTestSetup_GetChannel":ChannelDetailScreenTestSetup_GetChannel 
    "TestCase_populateInfoPanelItem":TestCase_populateInfoPanelItem 
    "TestCase_populateInfoPanelChannel":TestCase_populateInfoPanelChannel 
  } 

end function

function RBSFM_getFunctions_component_SpritePoster()
  return {
    "componentTest_SpritePoster":componentTest_SpritePoster 
  } 

end function

function RBSFM_getFunctions_componentTest_CategoryGridList()
  return {
    "componentTest_CategoryGridList":componentTest_CategoryGridList 
  } 

end function

function RBSFM_getFunctions_componentTest_ChannelDetailScreen()
  return {
    "componentTest_ChannelDetailScreen":componentTest_ChannelDetailScreen 
  } 

end function

function RBSFM_getFunctions_componentTest_DetailScreen()
  return {
    "componentTest_DetailScreen_AddQueue_History_Channel":componentTest_DetailScreen_AddQueue_History_Channel 
  } 

end function

function RBSFM_getFunctions_componentTest_InfoPanel()
  return {
    "componentTest_InfoPanel_movieMode":componentTest_InfoPanel_movieMode 
    "componentTest_InfoPanel_seriesMode":componentTest_InfoPanel_seriesMode 
    "componentTest_InfoPanel_categoryMode":componentTest_InfoPanel_categoryMode 
    "componentTest_InfoPanel_categoryScreen_itemMode":componentTest_InfoPanel_categoryScreen_itemMode 
  } 

end function

function RBSFM_getFunctions_componentTest_SettingsScreen()
  return {
    "componentTest_SettingsScreen":componentTest_SettingsScreen 
  } 

end function

function RBSFM_getFunctions_componentTest_TubiProgressBar()
  return {
    "componentTestHelper_ProgressBar":componentTestHelper_ProgressBar 
    "componentTest_ProgressBar_0":componentTest_ProgressBar_0 
    "componentTest_ProgressBar_0_1":componentTest_ProgressBar_0_1 
    "componentTest_ProgressBar_25":componentTest_ProgressBar_25 
    "componentTest_ProgressBar_50":componentTest_ProgressBar_50 
    "componentTest_ProgressBar_75":componentTest_ProgressBar_75 
    "componentTest_ProgressBar_100":componentTest_ProgressBar_100 
    "componentTest_ProgressBar_99":componentTest_ProgressBar_99 
    "componentTest_ProgressBar_150":componentTest_ProgressBar_150 
    "componentTest_ProgressBar_less_50":componentTest_ProgressBar_less_50 
    "componentTest_ProgressBar_width_0":componentTest_ProgressBar_width_0 
  } 

end function

function RBSFM_getFunctions_componentTest_VideoPlayer()
  return {
    "componentTest_VideoPlayer":componentTest_VideoPlayer 
  } 

end function

function RBSFM_getFunctions_test_CmsApi()
  return {
    "TestSuite_CmsApi":TestSuite_CmsApi 
    "CmsApiTestSuite_SetUp":CmsApiTestSuite_SetUp 
    "testCase_cmsApi_singleContentReq":testCase_cmsApi_singleContentReq 
    "testCase_cmsApi_singleContentReq_withChannels":testCase_cmsApi_singleContentReq_withChannels 
    "testCase_cmsApi_upNextContentReq":testCase_cmsApi_upNextContentReq 
    "testCase_cmsApi_upNextContentReq_withContainer":testCase_cmsApi_upNextContentReq_withContainer 
    "testCase_cmsApi_relatedContentReq":testCase_cmsApi_relatedContentReq 
    "testCase_cmsApi_thumbnailsReq":testCase_cmsApi_thumbnailsReq 
    "testCase_cmsApi_channelReq":testCase_cmsApi_channelReq 
    "testCase_cmsApi_homeScreenReq":testCase_cmsApi_homeScreenReq 
    "testCase_cmsApi_categoryReq":testCase_cmsApi_categoryReq 
    "testCase_cmsApi_searchReq":testCase_cmsApi_searchReq 
  } 

end function

function RBSFM_getFunctions_StringUtilsUnitTests()
  return {
    "StringUtilsSetup":StringUtilsSetup 
    "stringUtils_padString_test":stringUtils_padString_test 
    "stringUtils_formatLengthAsTimestamp_test":stringUtils_formatLengthAsTimestamp_test 
    "stringUtils_formatLengthAsEnglish_test":stringUtils_formatLengthAsEnglish_test 
    "stringUtils_capitalize_test":stringUtils_capitalize_test 
  } 

end function

function RBSFM_getFunctions_test_Request()
  return {
    "TestSuite_Request":TestSuite_Request 
    "testCase_request_createAsync":testCase_request_createAsync 
    "testCase_request_startWithPort":testCase_request_startWithPort 
    "testCase_request_startWithUrlTransfer":testCase_request_startWithUrlTransfer 
    "testCase_request_cancel":testCase_request_cancel 
    "testCase_request_handleEvent":testCase_request_handleEvent 
    "testCase_request_addParamsToUrlAsModuleFunction":testCase_request_addParamsToUrlAsModuleFunction 
    "testCase_request_addParamsToUrl":testCase_request_addParamsToUrl 
    "testCase_request_isHttps":testCase_request_isHttps 
    "testCase_request_methods":testCase_request_methods 
    "testHelper_request_createTestServer":testHelper_request_createTestServer 
  } 

end function

function RBSFM_getFunctions_test_RequestQueue()
  return {
    "TestSuite_TubiRequestQueue":TestSuite_TubiRequestQueue 
    "testCase_tubiRequestQueue_create":testCase_tubiRequestQueue_create 
    "testCase_tubiRequestQueue_pushRequest":testCase_tubiRequestQueue_pushRequest 
    "testCase_tubiRequestQueue_cancelRequest":testCase_tubiRequestQueue_cancelRequest 
    "testCase_tubiRequestQueue_clear":testCase_tubiRequestQueue_clear 
    "testCase_tubiRequestQueue_maxSize":testCase_tubiRequestQueue_maxSize 
    "testCase_tubiRequestQueue_handleEvent":testCase_tubiRequestQueue_handleEvent 
    "testCase_tubiRequestQueue_timeout":testCase_tubiRequestQueue_timeout 
  } 

end function

function RBSFM_getFunctions_test_Sentry()
  return {
    "TestSuite_Sentry":TestSuite_Sentry 
    "testCase_sentry_constructor":testCase_sentry_constructor 
    "testCase_sentry_parseDsn":testCase_sentry_parseDsn 
    "testCase_sentry_deepAppend":testCase_sentry_deepAppend 
    "testCase_sentry_captureMessage":testCase_sentry_captureMessage 
    "testCase_sentry_getUrl":testCase_sentry_getUrl 
  } 

end function

function RBSFM_getFunctions_test_StringUtils()
  return {
    "TestSuite_StringUtils":TestSuite_StringUtils 
    "testCase_stringUtils_padString":testCase_stringUtils_padString 
    "testCase_stringUtils_FormatLengthAsTimestamp":testCase_stringUtils_FormatLengthAsTimestamp 
    "testCase_stringUtils_formatLengthAsEnglish":testCase_stringUtils_formatLengthAsEnglish 
    "testCase_stringUtils_capitalize":testCase_stringUtils_capitalize 
  } 

end function

function RBSFM_getFunctions_test_TubiAds()
  return {
    "TestSuite_TubiAds":TestSuite_TubiAds 
    "testCase_tubiAds_getAdsListViaRoku":testCase_tubiAds_getAdsListViaRoku 
    "testHelper_tubiAds_createTubiAds":testHelper_tubiAds_createTubiAds 
  } 

end function

function RBSFM_getFunctions_test_TubiAuth()
  return {
    "TestSuite_TubiAuth":TestSuite_TubiAuth 
    "testCase_tubiAuth_refreshAuthToken":testCase_tubiAuth_refreshAuthToken 
    "testCase_tubiAuth_refreshAuthToken_failed":testCase_tubiAuth_refreshAuthToken_failed 
    "testCase_tubiAuth_refreshAuthToken_403":testCase_tubiAuth_refreshAuthToken_403 
    "testCase_tubiAuth_formatAuthInfoFromServer":testCase_tubiAuth_formatAuthInfoFromServer 
    "testCase_tubiAuth_checkIfAuthExpired":testCase_tubiAuth_checkIfAuthExpired 
    "testCase_tubiAuth_updateAuthInfo":testCase_tubiAuth_updateAuthInfo 
    "testCase_tubiAuth_getAuthHeaders":testCase_tubiAuth_getAuthHeaders 
    "testCase_tubiAuth_saveAuthInfo":testCase_tubiAuth_saveAuthInfo 
    "testCase_tubiAuth_deleteAuthInfo":testCase_tubiAuth_deleteAuthInfo 
    "testCase_tubiAuth_requestTokenRefresh":testCase_tubiAuth_requestTokenRefresh 
    "testCase_tubiAuth_requestTokenTransfer":testCase_tubiAuth_requestTokenTransfer 
    "testCase_tubiAuth_handleRefreshResponse":testCase_tubiAuth_handleRefreshResponse 
    "testCase_tubiAuth_handleRefreshResponse_403":testCase_tubiAuth_handleRefreshResponse_403 
    "testCase_tubiAuth_createAuthRequest":testCase_tubiAuth_createAuthRequest 
    "testCase_tubiAuth_transferRefreshToken":testCase_tubiAuth_transferRefreshToken 
    "testCase_tubiAuth_transferRefreshToken_failed":testCase_tubiAuth_transferRefreshToken_failed 
    "testCase_tubiAuth_transferRefreshToken_403":testCase_tubiAuth_transferRefreshToken_403 
    "testHelper_tubiAuth_createMetadataFetchTaskServer":testHelper_tubiAuth_createMetadataFetchTaskServer 
    "testCase_tubiAuth_getFirstVisit":testCase_tubiAuth_getFirstVisit 
    "testCase_tubiAuth_setFirstVisit":testCase_tubiAuth_setFirstVisit 
    "testCase_tubiAuth_getKidsMode":testCase_tubiAuth_getKidsMode 
    "testCase_tubiAuth_getDefaultKidsMode":testCase_tubiAuth_getDefaultKidsMode 
    "testCase_tubiAuth_setKidsMode":testCase_tubiAuth_setKidsMode 
  } 

end function

function RBSFM_getFunctions_test_TubiBookmarks()
  return {
    "TestSuite_TubiBookmarks":TestSuite_TubiBookmarks 
    "testHelper_tubiBookmarks_mockAuth_Unauthorized":testHelper_tubiBookmarks_mockAuth_Unauthorized 
    "testHelper_tubiBookmarks_mockAuth_Authorized":testHelper_tubiBookmarks_mockAuth_Authorized 
    "testCase_tubiBookmarks_addBookmarkReqUnauthorized":testCase_tubiBookmarks_addBookmarkReqUnauthorized 
    "testCase_tubiBookmarks_addBookmarkReqMovie":testCase_tubiBookmarks_addBookmarkReqMovie 
    "testCase_tubiBookmarks_addBookmarkReqSeries":testCase_tubiBookmarks_addBookmarkReqSeries 
    "testCase_tubiBookmarks_addBookmarkReqEpisodeWithParent":testCase_tubiBookmarks_addBookmarkReqEpisodeWithParent 
    "testCase_tubiBookmarks_removeBookmarkReq":testCase_tubiBookmarks_removeBookmarkReq 
    "testCase_tubiBookmarks_addHistoryReqVideo":testCase_tubiBookmarks_addHistoryReqVideo 
    "testCase_tubiBookmarks_addHistoryReqEpisodeWithParent":testCase_tubiBookmarks_addHistoryReqEpisodeWithParent 
    "testCase_tubiBookmarks_addHistoryReqEpisodeWithoutParent":testCase_tubiBookmarks_addHistoryReqEpisodeWithoutParent 
    "testCase_tubiBookmarks_addHistoryReqSeries":testCase_tubiBookmarks_addHistoryReqSeries 
    "testCase_tubiBookmarks_getInitialBookmarksReqSignedOut":testCase_tubiBookmarks_getInitialBookmarksReqSignedOut 
    "testCase_tubiBookmarks_getInitialBookmarksReqSignedIn":testCase_tubiBookmarks_getInitialBookmarksReqSignedIn 
    "testCase_tubiBookmarks_getInitialHistoryReqSignedOut":testCase_tubiBookmarks_getInitialHistoryReqSignedOut 
    "testCase_tubiBookmarks_getInitialHistoryReqSignedOutGuestHistoryEnabled":testCase_tubiBookmarks_getInitialHistoryReqSignedOutGuestHistoryEnabled 
    "testCase_tubiBookmarks_getInitialHistoryReqSignedIn":testCase_tubiBookmarks_getInitialHistoryReqSignedIn 
    "testCase_tubiBookmarks_handleInitialBookmarks":testCase_tubiBookmarks_handleInitialBookmarks 
    "testCase_tubiBookmarks_handleInitialHistory":testCase_tubiBookmarks_handleInitialHistory 
  } 

end function

function RBSFM_getFunctions_test_TubiExperiments()
  return {
    "TestSuite_TubiExperiments":TestSuite_TubiExperiments 
    "testCase_tubiExperiments_initSuccess":testCase_tubiExperiments_initSuccess 
    "testCase_tubiExperiments_initFailed":testCase_tubiExperiments_initFailed 
    "testCase_tubiExperiments_getExperimentValueValid":testCase_tubiExperiments_getExperimentValueValid 
    "testCase_tubiExperiments_getExperimentValueDefault":testCase_tubiExperiments_getExperimentValueDefault 
    "testCase_tubiExperiments_getExperimentValueInvalid":testCase_tubiExperiments_getExperimentValueInvalid 
    "testHelper_tubiExperiments_mockGetInvalidNamespaces":testHelper_tubiExperiments_mockGetInvalidNamespaces 
    "testHelper_tubiExperiments_mockGetNamespaces":testHelper_tubiExperiments_mockGetNamespaces 
  } 

end function

function RBSFM_getFunctions_test_TubiExternalConfig()
  return {
    "TestSuite_TubiExternalConfig":TestSuite_TubiExternalConfig 
    "testCase_tubiExternalConfig_initSuccess":testCase_tubiExternalConfig_initSuccess 
    "testCase_tubiExternalConfig_initDefaults":testCase_tubiExternalConfig_initDefaults 
    "testCase_tubiExternalConfig_initFailed":testCase_tubiExternalConfig_initFailed 
    "testHelper_tubiExternalConfig_mockGetInvalidConfigs":testHelper_tubiExternalConfig_mockGetInvalidConfigs 
    "testHelper_tubiExternalConfig_mockGetConfigs":testHelper_tubiExternalConfig_mockGetConfigs 
  } 

end function

function RBSFM_getFunctions_test_TubiLogger()
  return {
    "TestSuite_TubiLogger":TestSuite_TubiLogger 
    "testCase_tubiLogger_getLogPrintout":testCase_tubiLogger_getLogPrintout 
    "testCase_tubiLogger_buildLogInfo":testCase_tubiLogger_buildLogInfo 
    "testCase_tubiLogger_getLoggingRequest":testCase_tubiLogger_getLoggingRequest 
    "testCase_tubiLogger_sendLogging":testCase_tubiLogger_sendLogging 
  } 

end function

function RBSFM_getFunctions_test_tubimetadatatranslate()
  return {
    "TestSuite_TubiMetadataTranslate":TestSuite_TubiMetadataTranslate 
    "TubiMetadataTranslateTestSuite_SetUp":TubiMetadataTranslateTestSuite_SetUp 
    "testCase_tubiMetadataTranslate_translateRecursive_testTranslateTypes":testCase_tubiMetadataTranslate_translateRecursive_testTranslateTypes 
    "testCase_tubiMetadataTranslate_translateRecursive_testParentTypes":testCase_tubiMetadataTranslate_translateRecursive_testParentTypes 
    "testCase_tubiMetadataTranslate_translateRecursive_testCreditsCuepoints":testCase_tubiMetadataTranslate_translateRecursive_testCreditsCuepoints 
    "testCase_tubiMetadataTranslate_translateRecursive_channel":testCase_tubiMetadataTranslate_translateRecursive_channel 
    "testCase_tubiMetadataTranslate_translateRecursive_series":testCase_tubiMetadataTranslate_translateRecursive_series 
    "testCase_tubiMetadataTranslate_translateRecursive_videoResources":testCase_tubiMetadataTranslate_translateRecursive_videoResources 
    "testCase_tubiMetadataTranslate_translateContainer_category":testCase_tubiMetadataTranslate_translateContainer_category 
    "testCase_tubiMetadataTranslate_translateContainer_channel":testCase_tubiMetadataTranslate_translateContainer_channel 
    "testCase_tubiMetadataTranslate_translateHomescreen":testCase_tubiMetadataTranslate_translateHomescreen 
    "testCase_tubiMetadataTranslate_translate":testCase_tubiMetadataTranslate_translate 
    "testCase_tubiMetadataTranslate_translateChannel":testCase_tubiMetadataTranslate_translateChannel 
    "testCase_tubiMetadataTranslate_getContentFromCategoryJson":testCase_tubiMetadataTranslate_getContentFromCategoryJson 
    "testCase_tubiMetadataTranslate_generateChannelPosterUrl":testCase_tubiMetadataTranslate_generateChannelPosterUrl 
    "testCase_tubiMetadataTranslate_generateChannelPosterUrl_unbranded":testCase_tubiMetadataTranslate_generateChannelPosterUrl_unbranded 
  } 

end function

function RBSFM_getFunctions_test_TubiNodeHelpers()
  return {
    "TestSuite_TubiNodeHelpers":TestSuite_TubiNodeHelpers 
    "testCase_tubiNodeHelpers_getChildIndex":testCase_tubiNodeHelpers_getChildIndex 
    "testCase_tubiNodeHelpers_getChildIndexById":testCase_tubiNodeHelpers_getChildIndexById 
    "testCase_tubiNodeHelpers_convertNodesToIdsAA":testCase_tubiNodeHelpers_convertNodesToIdsAA 
    "testCase_tubiNodeHelpers_immutableInsertChild":testCase_tubiNodeHelpers_immutableInsertChild 
    "testCase_tubiNodeHelpers_immutableInsertChildAlreadyExists":testCase_tubiNodeHelpers_immutableInsertChildAlreadyExists 
    "testCase_tubiNodeHelpers_immutableRemoveChildIndex":testCase_tubiNodeHelpers_immutableRemoveChildIndex 
    "testCase_tubiNodeHelpers_immutableRemoveChild":testCase_tubiNodeHelpers_immutableRemoveChild 
    "testCase_tubiNodeHelpers_immutableRemoveChildren":testCase_tubiNodeHelpers_immutableRemoveChildren 
  } 

end function

function RBSFM_getFunctions_test_TubiTracking()
  return {
    "TestSuite_TubiTracking":TestSuite_TubiTracking 
    "testHelper_tubiTracking_createTubiTracking":testHelper_tubiTracking_createTubiTracking 
    "testCase_tubiTracking_getAnalyticsRequestIdempotency":testCase_tubiTracking_getAnalyticsRequestIdempotency 
    "testCase_tubiTracking_getAnalyticsTimestamp":testCase_tubiTracking_getAnalyticsTimestamp 
    "testCase_tubiTracking_getAnalyticsUser":testCase_tubiTracking_getAnalyticsUser 
    "testCase_tubiTracking_getAnalyticsDevice":testCase_tubiTracking_getAnalyticsDevice 
    "testCase_tubiTracking_getAnalyticsApp":testCase_tubiTracking_getAnalyticsApp 
    "testCase_tubiTracking_getAnalyticsConnection":testCase_tubiTracking_getAnalyticsConnection 
    "testCase_tubiTracking_getAnalyticsEvent":testCase_tubiTracking_getAnalyticsEvent 
    "testCase_tubiTracking_getAnalyticsPage":testCase_tubiTracking_getAnalyticsPage 
    "testCase_tubiTracking_getAnalyticsComponent":testCase_tubiTracking_getAnalyticsComponent 
    "testCase_tubiTracking_getAnalyticsTile":testCase_tubiTracking_getAnalyticsTile 
    "testCase_tubiTracking_getAnalyticsAdAdrise":testCase_tubiTracking_getAnalyticsAdAdrise 
    "testCase_tubiTracking_getAnalyticsAdRainmaker":testCase_tubiTracking_getAnalyticsAdRainmaker 
    "testCase_tubiTracking_populateMessage":testCase_tubiTracking_populateMessage 
    "testCase_tubiTracking_isEmptyValue":testCase_tubiTracking_isEmptyValue 
    "testCase_tubiTracking_isNumeric":testCase_tubiTracking_isNumeric 
  } 

end function

function RBSFM_getFunctions_test_Settings()
  return {
    "TestSuite_Settings":TestSuite_Settings 
    "testCase_settings_getSettings":testCase_settings_getSettings 
    "testCase_settings_getManifest":testCase_settings_getManifest 
  } 

end function

function RBSFM_getFilenames()
  return [
    "Test_VideoPlayer_Cuepoints", 
    "Test_VideoPlayer_VideoErrorHelpers", 
    "Test_VideoPlayer_VideoPlayerHelpers", 
    "Test_ChannelDetailScreen_Helpers", 
    "component_SpritePoster", 
    "componentTest_CategoryGridList", 
    "componentTest_ChannelDetailScreen", 
    "componentTest_DetailScreen", 
    "componentTest_InfoPanel", 
    "componentTest_SettingsScreen", 
    "componentTest_TubiProgressBar", 
    "componentTest_VideoPlayer", 
    "test_CmsApi", 
    "StringUtilsUnitTests", 
    "test_Request", 
    "test_RequestQueue", 
    "test_Sentry", 
    "test_StringUtils", 
    "test_TubiAds", 
    "test_TubiAuth", 
    "test_TubiBookmarks", 
    "test_TubiExperiments", 
    "test_TubiExternalConfig", 
    "test_TubiLogger", 
    "test_tubimetadatatranslate", 
    "test_TubiNodeHelpers", 
    "test_TubiTracking", 
    "test_Settings", 
  ] 
end function




    function RBSFM_getRuntimeConfig()
        return {
          "failFast": false
          "logLevel": 2
          "showOnlyFailures": false
          "printLcov": false
          "rooibosPreprocessorVersion": 1.3.0
          "port": Invalid
          }
    end function
    

    function RBSFM_getPreprocessorVersion()
        return "1.3.0"
    end function
    

    '***************************************************
    ' Unit test suites defitintions
    '***************************************************
    

    function RBSFM_getTestSuitesForProject()
        return [
        
{
      name: "[StringUtils] StringUtils.brs"
      filePath: "source/tests/rooibos/specs/lib/StringUtilsUnitTests.brs"
      valid: true
      hasFailures: false
      hasSoloTests: false
      hasIgnoredTests: false
      hasSoloGroups: false
      isSolo: false
      isIgnored: false
      itGroups: [
      {
        testCases: [
        {
          isSolo: false
          funcName: "stringUtils_padString_test"
          isIgnored: false
          isParamTest: false
          name: "padString unit tests"
          lineNumber: 14
          paramLineNumber: 0
          assertIndex: 5
          assertLineNumberMap: {"0":18,"1":22,"2":25,"3":28,"4":29}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "stringUtils_formatLengthAsTimestamp_test"
          isIgnored: false
          isParamTest: false
          name: "formatLengthAsTimestamp unit tests"
          lineNumber: 34
          paramLineNumber: 0
          assertIndex: 4
          assertLineNumberMap: {"0":35,"1":36,"2":39,"3":40}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "stringUtils_formatLengthAsEnglish_test"
          isIgnored: false
          isParamTest: false
          name: "formatLengthAsEnglish unit tests"
          lineNumber: 46
          paramLineNumber: 0
          assertIndex: 5
          assertLineNumberMap: {"0":47,"1":48,"2":49,"3":50,"4":51}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "stringUtils_capitalize_test"
          isIgnored: false
          isParamTest: false
          name: "capitalize unit tests"
          lineNumber: 56
          paramLineNumber: 0
          assertIndex: 4
          assertLineNumberMap: {"0":57,"1":58,"2":59,"3":60}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "StringUtilsUnitTests"
        setupFunctionName: "StringUtilsSetup"
        tearDownFunctionName: ""
        beforeEachFunctionName: ""
        afterEachFunctionName: ""
        isSolo: false
        isLegacy: false
        isIgnored: false
        hasSoloTests: false
        name: "tests functions in StringUtils.brs"
      }]
      setupFunctionName: "StringUtilsSetup"
      tearDownFunctionName: ""
      isNodeTest: false
      isLegacy: false
      nodeTestFileName: ""
      beforeEachFunctionName: ""
      afterEachFunctionName: ""
    },

      ]
    end function


    function RBSFM_getIgnoredTestInfo()
        return {
          "count": 0
          "items":[
        
      ]}
    end function



    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    