
    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    

    '***************************************************
    'Function maps
    '***************************************************
    function RBSFM_getFunctionsForFile(filename)
  map = {
    "ChannelDetailScreen_UnitTests":RBSFM_getFunctions_ChannelDetailScreen_UnitTests 
    "VideoPlayer_VideoErrorHelpersUnitTests":RBSFM_getFunctions_VideoPlayer_VideoErrorHelpersUnitTests 
    "VideoPlayer_VideoPlayerCuepointsUnitTests":RBSFM_getFunctions_VideoPlayer_VideoPlayerCuepointsUnitTests 
    "VideoPlayer_VideoPlayerHelpersUnitTests":RBSFM_getFunctions_VideoPlayer_VideoPlayerHelpersUnitTests 
    "CmsApiIntegrationTests":RBSFM_getFunctions_CmsApiIntegrationTests 
    "CmsApiUnitTests":RBSFM_getFunctions_CmsApiUnitTests 
    "GeneralTaskModuleUnitTests":RBSFM_getFunctions_GeneralTaskModuleUnitTests 
    "RequestQueueUnitTests":RBSFM_getFunctions_RequestQueueUnitTests 
    "RequestUnitTests":RBSFM_getFunctions_RequestUnitTests 
    "SentryUnitTests":RBSFM_getFunctions_SentryUnitTests 
    "SettingsUnitTests":RBSFM_getFunctions_SettingsUnitTests 
    "StringUtilsUnitTests":RBSFM_getFunctions_StringUtilsUnitTests 
    "TubiAdsUnitTests":RBSFM_getFunctions_TubiAdsUnitTests 
    "TubiAuthUnitTests":RBSFM_getFunctions_TubiAuthUnitTests 
    "TubiBookmarksUnitTests":RBSFM_getFunctions_TubiBookmarksUnitTests 
    "TubiExperimentsUnitTests":RBSFM_getFunctions_TubiExperimentsUnitTests 
    "TubiExternalConfigUnitTests":RBSFM_getFunctions_TubiExternalConfigUnitTests 
    "TubiLoggerUnitTests":RBSFM_getFunctions_TubiLoggerUnitTests 
    "TubiMetadataTranslateUnitTests":RBSFM_getFunctions_TubiMetadataTranslateUnitTests 
    "TubiNodeHelpersUnitTests":RBSFM_getFunctions_TubiNodeHelpersUnitTests 
    "TubiTrackingUnitTests":RBSFM_getFunctions_TubiTrackingUnitTests 
    "YoSpaceId3sTest":RBSFM_getFunctions_YoSpaceId3sTest 
  } 
  return map[filename]
end function

function RBSFM_getFunctions_ChannelDetailScreen_UnitTests()
  return {
    "channelDetailScreenSetup":channelDetailScreenSetup 
    "channelDetailScreen_populateInfoPanelItem_test":channelDetailScreen_populateInfoPanelItem_test 
    "channelDetailScreen_populateInfoPanelChannel_test":channelDetailScreen_populateInfoPanelChannel_test 
  } 

end function

function RBSFM_getFunctions_VideoPlayer_VideoErrorHelpersUnitTests()
  return {
    "VideoErrorsSetup":VideoErrorsSetup 
    "videoHelpers_getPlaybackErrorInfo_test":videoHelpers_getPlaybackErrorInfo_test 
    "videoHelpers_getPlaybackErrorInfo_Position0":videoHelpers_getPlaybackErrorInfo_Position0 
    "videoHelpers_getPlaybackErrorInfo_Error3":videoHelpers_getPlaybackErrorInfo_Error3 
    "videoHelpers_getPlaybackErrorInfo_Error3_Position0":videoHelpers_getPlaybackErrorInfo_Error3_Position0 
    "videoHelpers_removeExcessUrl":videoHelpers_removeExcessUrl 
  } 

end function

function RBSFM_getFunctions_VideoPlayer_VideoPlayerCuepointsUnitTests()
  return {
    "videoCuepoints_isInWindow_test":videoCuepoints_isInWindow_test 
    "videoCuepoints_isAtPosition_test":videoCuepoints_isAtPosition_test 
  } 

end function

function RBSFM_getFunctions_VideoPlayer_VideoPlayerHelpersUnitTests()
  return {
    "VideoPlayerSetup":VideoPlayerSetup 
    "isActiveVideoState_test":isActiveVideoState_test 
    "isButtonPressAllowed_test":isButtonPressAllowed_test 
  } 

end function

function RBSFM_getFunctions_CmsApiIntegrationTests()
  return {
    "CmsApiIntegrationSetup":CmsApiIntegrationSetup 
    "cmsApi_channelReq_integration_test":cmsApi_channelReq_integration_test 
    "cmsApi_homeScreenReq_integration_test":cmsApi_homeScreenReq_integration_test 
    "cmsApi_categoryReq_integration_test":cmsApi_categoryReq_integration_test 
    "cmsApi_searchReq_integration_test":cmsApi_searchReq_integration_test 
  } 

end function

function RBSFM_getFunctions_CmsApiUnitTests()
  return {
    "CmsApiSetup":CmsApiSetup 
    "cmsApi_relatedContentReqInfo_test":cmsApi_relatedContentReqInfo_test 
    "cmsApi_getUpNextContentRequestInfo_test":cmsApi_getUpNextContentRequestInfo_test 
    "cmsApi_singleContentReqInfo_test":cmsApi_singleContentReqInfo_test 
    "cmsApi_thumbnailsReqInfo_test":cmsApi_thumbnailsReqInfo_test 
    "cmsApi_channelReq_test":cmsApi_channelReq_test 
    "cmsApi_homeScreenReq_test":cmsApi_homeScreenReq_test 
    "cmsApi_channelsCategoriesScreenReq_test":cmsApi_channelsCategoriesScreenReq_test 
    "cmsApi_categoryReq_test":cmsApi_categoryReq_test 
    "cmsApi_searchReq_test":cmsApi_searchReq_test 
    "cmsApi_commonOptions_test":cmsApi_commonOptions_test 
    "cmsApi_createAuthRequest_test":cmsApi_createAuthRequest_test 
    "cmsApi_setImageParams_test":cmsApi_setImageParams_test 
    "cmsApi_setTupianPosterParam_test":cmsApi_setTupianPosterParam_test 
    "cmsApi_setTupianLandscapeParam_test":cmsApi_setTupianLandscapeParam_test 
    "cmsApi_setTupianLargeVitgParam_test":cmsApi_setTupianLargeVitgParam_test 
  } 

end function

function RBSFM_getFunctions_GeneralTaskModuleUnitTests()
  return {
    "GeneralTaskModuleSetup":GeneralTaskModuleSetup 
    "generalTaskModule_makeRequest_test":generalTaskModule_makeRequest_test 
    "generalTaskModule_getGeneralTaskSuccessCallback_test":generalTaskModule_getGeneralTaskSuccessCallback_test 
    "generalTaskModule_getGeneralTaskErrorCallback_test":generalTaskModule_getGeneralTaskErrorCallback_test 
    "generalTaskModule_storeGeneralTaskCallbacks_test":generalTaskModule_storeGeneralTaskCallbacks_test 
    "onSuccessCallbackTest":onSuccessCallbackTest 
    "onErrorCallbackTest":onErrorCallbackTest 
  } 

end function

function RBSFM_getFunctions_RequestQueueUnitTests()
  return {
    "TubiRequestQueueSetup":TubiRequestQueueSetup 
    "tubiRequestQueue_BeforeEach":tubiRequestQueue_BeforeEach 
    "tubiRequestQueue_create_test":tubiRequestQueue_create_test 
    "tubiRequestQueue_pushRequest_test":tubiRequestQueue_pushRequest_test 
    "tubiRequestQueue_cancelRequest_test":tubiRequestQueue_cancelRequest_test 
    "tubiRequestQueue_clear_test":tubiRequestQueue_clear_test 
    "tubiRequestQueue_maxSize_test":tubiRequestQueue_maxSize_test 
    "tubiRequestQueue_handleEvent_test":tubiRequestQueue_handleEvent_test 
    "tubiRequestQueue_timeout_test":tubiRequestQueue_timeout_test 
  } 

end function

function RBSFM_getFunctions_RequestUnitTests()
  return {
    "RequestSetup":RequestSetup 
    "request_createAsync_test":request_createAsync_test 
    "request_startWithPort_test":request_startWithPort_test 
    "request_startWithUrlTransfer_test":request_startWithUrlTransfer_test 
    "request_cancel_test":request_cancel_test 
    "request_handleEvent_test":request_handleEvent_test 
    "request_addParamsToUrlAsModuleFunction_test":request_addParamsToUrlAsModuleFunction_test 
    "request_addParamsToUrl_test":request_addParamsToUrl_test 
    "request_isHttps_test":request_isHttps_test 
    "request_methods_test":request_methods_test 
    "request_createTestServer_testHelper":request_createTestServer_testHelper 
  } 

end function

function RBSFM_getFunctions_SentryUnitTests()
  return {
    "SentrySetup":SentrySetup 
    "sentry_constructor_test":sentry_constructor_test 
    "tsentry_parseDsn_test":tsentry_parseDsn_test 
    "sentry_deepAppend_test":sentry_deepAppend_test 
    "sentry_captureMessage_test":sentry_captureMessage_test 
    "sentry_getUrl_test":sentry_getUrl_test 
  } 

end function

function RBSFM_getFunctions_SettingsUnitTests()
  return {
    "SettingsSetup":SettingsSetup 
    "settings_getSettings_test":settings_getSettings_test 
    "settings_getManifest_test":settings_getManifest_test 
  } 

end function

function RBSFM_getFunctions_StringUtilsUnitTests()
  return {
    "StringUtilsSetup":StringUtilsSetup 
    "stringUtils_padString_test":stringUtils_padString_test 
    "stringUtils_formatLengthAsTimestamp_test":stringUtils_formatLengthAsTimestamp_test 
    "stringUtils_formatLengthAsEnglish_test":stringUtils_formatLengthAsEnglish_test 
    "stringUtils_capitalize_test":stringUtils_capitalize_test 
    "stringUtils_getUrlParts_test":stringUtils_getUrlParts_test 
  } 

end function

function RBSFM_getFunctions_TubiAdsUnitTests()
  return {
    "TubiAdsSetup":TubiAdsSetup 
    "tubiAds_getAdsListViaRoku_failure_test":tubiAds_getAdsListViaRoku_failure_test 
    "testHelper_tubiAds_createTubiAds_test":testHelper_tubiAds_createTubiAds_test 
  } 

end function

function RBSFM_getFunctions_TubiAuthUnitTests()
  return {
    "TubiAuthSetup":TubiAuthSetup 
    "tubiAuth_refreshAuthToken_test":tubiAuth_refreshAuthToken_test 
    "tubiAuth_refreshAuthToken_failed_test":tubiAuth_refreshAuthToken_failed_test 
    "tubiAuth_refreshAuthToken_403_test":tubiAuth_refreshAuthToken_403_test 
    "tubiAuth_formatAuthInfoFromServer_test":tubiAuth_formatAuthInfoFromServer_test 
    "tubiAuth_checkIfAuthExpired_test":tubiAuth_checkIfAuthExpired_test 
    "tubiAuth_updateAuthInfo_test":tubiAuth_updateAuthInfo_test 
    "tubiAuth_getAuthHeaders_test":tubiAuth_getAuthHeaders_test 
    "tubiAuth_saveAuthInfo_test":tubiAuth_saveAuthInfo_test 
    "tubiAuth_deleteAuthInfo_test":tubiAuth_deleteAuthInfo_test 
    "tubiAuth_requestTokenRefresh_test":tubiAuth_requestTokenRefresh_test 
    "tubiAuth_requestTokenTransfer_test":tubiAuth_requestTokenTransfer_test 
    "tubiAuth_handleRefreshResponse_test":tubiAuth_handleRefreshResponse_test 
    "tubiAuth_handleRefreshResponse_403":tubiAuth_handleRefreshResponse_403 
    "tubiAuth_createAuthRequest_test":tubiAuth_createAuthRequest_test 
    "tubiAuth_transferRefreshToken_test":tubiAuth_transferRefreshToken_test 
    "tubiAuth_transferRefreshToken_failed_test":tubiAuth_transferRefreshToken_failed_test 
    "tubiAuth_transferRefreshToken_403_test":tubiAuth_transferRefreshToken_403_test 
    "tubiAuth_createMetadataFetchTaskServer_testHelper":tubiAuth_createMetadataFetchTaskServer_testHelper 
    "tubiAuth_visit_BeforeEach":tubiAuth_visit_BeforeEach 
    "tubiAuth_getFirstVisit_test":tubiAuth_getFirstVisit_test 
    "tubiAuth_setFirstVisit_test":tubiAuth_setFirstVisit_test 
  } 

end function

function RBSFM_getFunctions_TubiBookmarksUnitTests()
  return {
    "TubiBookmarksSetup":TubiBookmarksSetup 
    "tubiBookmarks_mockAuth_Unauthorized_testHelper":tubiBookmarks_mockAuth_Unauthorized_testHelper 
    "tubiBookmarks_mockAuth_Authorized_testHelper":tubiBookmarks_mockAuth_Authorized_testHelper 
    "tubiBookmarks_addBookmarkReqUnauthorized_test":tubiBookmarks_addBookmarkReqUnauthorized_test 
    "tubiBookmarks_addBookmarkReqMovie_test":tubiBookmarks_addBookmarkReqMovie_test 
    "tubiBookmarks_addBookmarkReqSeries_test":tubiBookmarks_addBookmarkReqSeries_test 
    "tubiBookmarks_addBookmarkReqEpisodeWithParent_test":tubiBookmarks_addBookmarkReqEpisodeWithParent_test 
    "tubiBookmarks_removeBookmarkReq_test":tubiBookmarks_removeBookmarkReq_test 
    "tubiBookmarks_removeBookmarkLocallySuccessful_test":tubiBookmarks_removeBookmarkLocallySuccessful_test 
    "tubiBookmarks_addBookmarkLocallySuccessful_test":tubiBookmarks_addBookmarkLocallySuccessful_test 
    "tubiBookmarks_addBookmarkLocallySuccessfulForEpisode_test":tubiBookmarks_addBookmarkLocallySuccessfulForEpisode_test 
    "tubiBookmarks_addHistoryReqVideo_test":tubiBookmarks_addHistoryReqVideo_test 
    "tubiBookmarks_addHistoryReqEpisodeWithParent_test":tubiBookmarks_addHistoryReqEpisodeWithParent_test 
    "tubiBookmarks_addHistoryReqEpisodeWithoutParent_test":tubiBookmarks_addHistoryReqEpisodeWithoutParent_test 
    "tubiBookmarks_addHistoryReqSeries_test":tubiBookmarks_addHistoryReqSeries_test 
    "tubiBookmarks_getInitialBookmarksReqSignedOut_test":tubiBookmarks_getInitialBookmarksReqSignedOut_test 
    "tubiBookmarks_getInitialBookmarksReqSignedIn_test":tubiBookmarks_getInitialBookmarksReqSignedIn_test 
    "tubiBookmarks_getInitialHistoryReqSignedOut_test":tubiBookmarks_getInitialHistoryReqSignedOut_test 
    "tubiBookmarks_getInitialHistoryReqSignedIn_test":tubiBookmarks_getInitialHistoryReqSignedIn_test 
    "tubiBookmarks_handleInitialBookmarks_test":tubiBookmarks_handleInitialBookmarks_test 
    "tubiBookmarks_handleInitialHistory_test":tubiBookmarks_handleInitialHistory_test 
  } 

end function

function RBSFM_getFunctions_TubiExperimentsUnitTests()
  return {
    "TubiExperimentsSetup":TubiExperimentsSetup 
    "tubiExperiments_mockGetNamespaces_testHelper":tubiExperiments_mockGetNamespaces_testHelper 
    "tubiExperiments_initSuccess_test":tubiExperiments_initSuccess_test 
    "tubiExperiments_getExperimentValueValid_test":tubiExperiments_getExperimentValueValid_test 
    "tubiExperiments_getExperimentValueDefault_test":tubiExperiments_getExperimentValueDefault_test 
    "tubiExperiments_getExperimentValueInvalid_test":tubiExperiments_getExperimentValueInvalid_test 
    "tubiExperiments_mockGetInvalidNamespaces_testHelper":tubiExperiments_mockGetInvalidNamespaces_testHelper 
    "tubiExperiments_updateNamespaces":tubiExperiments_updateNamespaces 
    "tubiExperiments_initFailed_test":tubiExperiments_initFailed_test 
  } 

end function

function RBSFM_getFunctions_TubiExternalConfigUnitTests()
  return {
    "TubiExternalConfigSetup":TubiExternalConfigSetup 
    "tubiExternalConfig_mockGetInvalidConfigs_testHelper":tubiExternalConfig_mockGetInvalidConfigs_testHelper 
    "tubiExternalConfig_mockGetConfigs_testHelper":tubiExternalConfig_mockGetConfigs_testHelper 
    "tubiExternalConfig_config":tubiExternalConfig_config 
    "tubiExternalConfig_initSuccess_test":tubiExternalConfig_initSuccess_test 
    "tubiExternalConfig_initDefaults_test":tubiExternalConfig_initDefaults_test 
    "tubiExternalConfig_initFailed_test":tubiExternalConfig_initFailed_test 
  } 

end function

function RBSFM_getFunctions_TubiLoggerUnitTests()
  return {
    "TubiLoggerSetup":TubiLoggerSetup 
    "tubiLogger_getLogPrintout_test":tubiLogger_getLogPrintout_test 
    "tubiLogger_buildLogInfo_test":tubiLogger_buildLogInfo_test 
    "tubiLogger_getLoggingRequest_test":tubiLogger_getLoggingRequest_test 
    "tubiLogger_sendLogging_test":tubiLogger_sendLogging_test 
  } 

end function

function RBSFM_getFunctions_TubiMetadataTranslateUnitTests()
  return {
    "TubiMetadataTranslateSetup":TubiMetadataTranslateSetup 
    "tubiMetadataTranslate_translateRecursive_testTranslateTypes_test":tubiMetadataTranslate_translateRecursive_testTranslateTypes_test 
    "tubiMetadataTranslate_translateRecursive_testParentTypes_test":tubiMetadataTranslate_translateRecursive_testParentTypes_test 
    "tubiMetadataTranslate_translateRecursive_testCreditsCuepoints_test":tubiMetadataTranslate_translateRecursive_testCreditsCuepoints_test 
    "tubiMetadataTranslate_translateRecursive_channel_test":tubiMetadataTranslate_translateRecursive_channel_test 
    "tubiMetadataTranslate_translateRecursive_series_test":tubiMetadataTranslate_translateRecursive_series_test 
    "tubiMetadataTranslate_translateRecursive_videoResources_test":tubiMetadataTranslate_translateRecursive_videoResources_test 
    "tubiMetadataTranslate_translateContainer_category_test":tubiMetadataTranslate_translateContainer_category_test 
    "tubiMetadataTranslate_translateContainer_channel_test":tubiMetadataTranslate_translateContainer_channel_test 
    "tubiMetadataTranslate_translateHomescreen_test":tubiMetadataTranslate_translateHomescreen_test 
    "tubiMetadataTranslate_translate_test":tubiMetadataTranslate_translate_test 
    "tubiMetadataTranslate_translateChannel_test":tubiMetadataTranslate_translateChannel_test 
    "tubiMetadataTranslate_getContentFromCategoryJson_test":tubiMetadataTranslate_getContentFromCategoryJson_test 
    "tubiMetadataTranslate_generateChannelPosterUrl_test":tubiMetadataTranslate_generateChannelPosterUrl_test 
    "tubiMetadataTranslate_generateChannelPosterUrl_unbranded_test":tubiMetadataTranslate_generateChannelPosterUrl_unbranded_test 
  } 

end function

function RBSFM_getFunctions_TubiNodeHelpersUnitTests()
  return {
    "TubiNodeHelpersSetup":TubiNodeHelpersSetup 
    "tubiNodeHelpers_BeforeEach":tubiNodeHelpers_BeforeEach 
    "tubiNodeHelpers_getChildIndex_test":tubiNodeHelpers_getChildIndex_test 
    "tubiNodeHelpers_getChildIndexById_test":tubiNodeHelpers_getChildIndexById_test 
    "tubiNodeHelpers_convertNodesToIdsAA_test":tubiNodeHelpers_convertNodesToIdsAA_test 
    "tubiNodeHelpers_immutableInsertChild_test":tubiNodeHelpers_immutableInsertChild_test 
    "tubiNodeHelpers_immutableInsertChildAlreadyExists_test":tubiNodeHelpers_immutableInsertChildAlreadyExists_test 
    "tubiNodeHelpers_immutableRemoveChildIndex_test":tubiNodeHelpers_immutableRemoveChildIndex_test 
    "tubiNodeHelpers_immutableRemoveChild_test":tubiNodeHelpers_immutableRemoveChild_test 
    "tubiNodeHelpers_immutableRemoveChildren_test":tubiNodeHelpers_immutableRemoveChildren_test 
  } 

end function

function RBSFM_getFunctions_TubiTrackingUnitTests()
  return {
    "TubiTrackingSetup":TubiTrackingSetup 
    "tubiTracking_createTubiTracking_testHelper":tubiTracking_createTubiTracking_testHelper 
    "tubiTracking_getAnalyticsRequestIdempotency_test":tubiTracking_getAnalyticsRequestIdempotency_test 
    "tubiTracking_getAnalyticsTimestamp_test":tubiTracking_getAnalyticsTimestamp_test 
    "tubiTracking_getAnalyticsUser_test":tubiTracking_getAnalyticsUser_test 
    "tubiTracking_getAnalyticsDevice_test":tubiTracking_getAnalyticsDevice_test 
    "tubiTracking_getAnalyticsApp_test":tubiTracking_getAnalyticsApp_test 
    "tubiTracking_getAnalyticsConnection_test":tubiTracking_getAnalyticsConnection_test 
    "tubiTracking_getAnalyticsEvent_test":tubiTracking_getAnalyticsEvent_test 
    "tubiTracking_getAnalyticsPage_test":tubiTracking_getAnalyticsPage_test 
    "tubiTracking_getAnalyticsComponent_test":tubiTracking_getAnalyticsComponent_test 
    "tubiTracking_getAnalyticsTile_test":tubiTracking_getAnalyticsTile_test 
    "tubiTracking_getAnalyticsAdAdrise_test":tubiTracking_getAnalyticsAdAdrise_test 
    "tubiTracking_getAnalyticsAdRainmaker_test":tubiTracking_getAnalyticsAdRainmaker_test 
    "tubiTracking_populateMessage_test":tubiTracking_populateMessage_test 
    "tubiTracking_isEmptyValue_test":tubiTracking_isEmptyValue_test 
    "tubiTracking_isNumeric_test":tubiTracking_isNumeric_test 
  } 

end function

function RBSFM_getFunctions_YoSpaceId3sTest()
  return {
    "YoSpaceId3sSetup":YoSpaceId3sSetup 
    "YoSpaceId3s_beforeEach":YoSpaceId3s_beforeEach 
    "yoSpaceIds_setTag_start_test":yoSpaceIds_setTag_start_test 
    "yoSpaceIds_setTag_mid_test":yoSpaceIds_setTag_mid_test 
    "yoSpaceIds_setTag_end_test":yoSpaceIds_setTag_end_test 
    "yoSpaceIds_getTag_test":yoSpaceIds_getTag_test 
    "yoSpaceIds_getAllTags_test":yoSpaceIds_getAllTags_test 
    "yoSpaceIds_getId_test":yoSpaceIds_getId_test 
    "yoSpaceIds_getType_test":yoSpaceIds_getType_test 
    "yoSpaceIds_getPosition_test":yoSpaceIds_getPosition_test 
    "yoSpaceIds_currentSegment_test":yoSpaceIds_currentSegment_test 
    "yoSpaceIds_totalSegments_test":yoSpaceIds_totalSegments_test 
    "yoSpaceIds_clearTags_test":yoSpaceIds_clearTags_test 
  } 

end function

function RBSFM_getFilenames()
  return [
    "ChannelDetailScreen_UnitTests", 
    "VideoPlayer_VideoErrorHelpersUnitTests", 
    "VideoPlayer_VideoPlayerCuepointsUnitTests", 
    "VideoPlayer_VideoPlayerHelpersUnitTests", 
    "CmsApiIntegrationTests", 
    "CmsApiUnitTests", 
    "GeneralTaskModuleUnitTests", 
    "RequestQueueUnitTests", 
    "RequestUnitTests", 
    "SentryUnitTests", 
    "SettingsUnitTests", 
    "StringUtilsUnitTests", 
    "TubiAdsUnitTests", 
    "TubiAuthUnitTests", 
    "TubiBookmarksUnitTests", 
    "TubiExperimentsUnitTests", 
    "TubiExternalConfigUnitTests", 
    "TubiLoggerUnitTests", 
    "TubiMetadataTranslateUnitTests", 
    "TubiNodeHelpersUnitTests", 
    "TubiTrackingUnitTests", 
    "YoSpaceId3sTest", 
  ] 
end function




    function RBSFM_getRuntimeConfig()
        return {
          "failFast": false
          "logLevel": 2
          "showOnlyFailures": false
          "printLcov": false
          "rooibosPreprocessorVersion": "1.4.0"
          "port": Invalid
          }
    end function
    

    function RBSFM_getPreprocessorVersion()
        return "1.4.0"
    end function
    

    '***************************************************
    ' Unit test suites defitintions
    '***************************************************
    

    function RBSFM_getTestSuitesForProject()
        return [
        
{
      name: "[YoSpaceId3s] YoSpaceId3s.brs "
      filePath: "source/tests/rooibos/specs/lib/YoSpaceId3sTest.brs"
      valid: true
      hasFailures: false
      hasSoloTests: false
      hasIgnoredTests: false
      hasSoloGroups: true
      isSolo: true
      isIgnored: false
      itGroups: [
      {
        testCases: [
        {
          isSolo: false
          funcName: "yoSpaceIds_setTag_start_test"
          isIgnored: false
          isParamTest: false
          name: "setTag start id3 unit tests"
          lineNumber: 46
          paramLineNumber: 0
          assertIndex: 15
          assertLineNumberMap: {"0":49,"1":50,"2":51,"3":55,"4":56,"5":60,"6":61,"7":62,"8":63,"9":67,"10":69,"11":71,"12":75,"13":76,"14":80}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_setTag_mid_test"
          isIgnored: false
          isParamTest: false
          name: "setTag mid id3 unit tests"
          lineNumber: 85
          paramLineNumber: 0
          assertIndex: 6
          assertLineNumberMap: {"0":87,"1":88,"2":90,"3":91,"4":93,"5":94}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_setTag_end_test"
          isIgnored: false
          isParamTest: false
          name: "setTag end id3 unit tests"
          lineNumber: 99
          paramLineNumber: 0
          assertIndex: 6
          assertLineNumberMap: {"0":101,"1":102,"2":104,"3":105,"4":107,"5":108}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_getTag_test"
          isIgnored: false
          isParamTest: false
          name: "getTag unit tests"
          lineNumber: 113
          paramLineNumber: 0
          assertIndex: 5
          assertLineNumberMap: {"0":120,"1":121,"2":122,"3":123,"4":124}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_getAllTags_test"
          isIgnored: false
          isParamTest: false
          name: "getAllTags unit tests"
          lineNumber: 129
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":132}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_getId_test"
          isIgnored: false
          isParamTest: false
          name: "getId unit tests"
          lineNumber: 137
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":140}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_getType_test"
          isIgnored: false
          isParamTest: false
          name: "getType unit tests"
          lineNumber: 145
          paramLineNumber: 0
          assertIndex: 3
          assertLineNumberMap: {"0":148,"1":152,"2":156}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_getPosition_test"
          isIgnored: false
          isParamTest: false
          name: "getPosition unit tests"
          lineNumber: 161
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":164}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_currentSegment_test"
          isIgnored: false
          isParamTest: false
          name: "currentSegment unit tests"
          lineNumber: 169
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":172}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_totalSegments_test"
          isIgnored: false
          isParamTest: false
          name: "totalSegments unit tests"
          lineNumber: 177
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":180}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "yoSpaceIds_clearTags_test"
          isIgnored: false
          isParamTest: false
          name: "clearTags unit tests"
          lineNumber: 185
          paramLineNumber: 0
          assertIndex: 5
          assertLineNumberMap: {"0":188,"1":189,"2":190,"3":191,"4":192}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "YoSpaceId3sTest"
        setupFunctionName: "YoSpaceId3sSetup"
        tearDownFunctionName: ""
        beforeEachFunctionName: "YoSpaceId3s_beforeEach"
        afterEachFunctionName: ""
        isSolo: true
        isLegacy: false
        isIgnored: false
        hasSoloTests: false
        name: "tests functions in YoSpaceId3s.js"
      }]
      setupFunctionName: "YoSpaceId3sSetup"
      tearDownFunctionName: ""
      isNodeTest: false
      isLegacy: false
      nodeTestFileName: ""
      beforeEachFunctionName: "YoSpaceId3s_beforeEach"
      afterEachFunctionName: ""
    },

      ]
    end function


    function RBSFM_getIgnoredTestInfo()
        return {
          "count": 0
          "items":[
        
      ]}
    end function



    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    