# Some local docker helpers primarily aimed at running Travis-compatible builds via docker.  The purpose here
# is to allow off-line development and check Linux compatibility.
####

REPO_CONTAINER_PATH=/mnt/repo
REPO_LOCAL_PATH=${PWD}/..

DOCKER_IMAGE=tubi-linux

# A generic docker run command using circleci image
DOCKER_RUN=docker run -it \
  -v ${REPO_LOCAL_PATH}:${REPO_CONTAINER_PATH} \
  -w ${REPO_CONTAINER_PATH} \
  ${DOCKER_IMAGE}

.PHONY: docker-bash docker-env docker-build

# Get a bash shell within the container
docker-bash:
	${DOCKER_RUN} bash

# Print out the environment from within the container to verify settings
docker-env:
	${DOCKER_RUN} env

# Create a docker image that has some basic stuff we need for builds. This
# is mostly for convenience so we don't have to run a pre-build setup every
# time we want to test building on Linux
docker-build:
	docker build --no-cache -t ${DOCKER_IMAGE} .
