name: Draft Pull Request Actions

on:
  pull_request:
    types:
      - opened
      - converted_to_draft
      - ready_for_review
env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-remove-not-ready-label:
    runs-on: ubuntu-latest
    name: Add Remove Not Ready For Review Label
    steps:
    - uses: actions/checkout@v2

    # npm command install all required packages
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Run Workflow Code
      run: node ./js/workflows/draftPullRequest.js
