# This file executes the unit tests when PR is raised against master branch.
# This will be executed in Roku device available in SF office and logs will be captured in machine/server available in SF office.
# Device details can be found here : https://tubitv.atlassian.net/wiki/spaces/IT/pages/edit-v2/2465464321
# Roku IP address and password are taken from .env file from github action runner. If you update it, reboot the machine

name: Execute Unit tests

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch.
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run. self hosted machine is our own machine setup in SF office and it has dedicated connected roku device.
    runs-on: self-hosted
    # timeouts after 10 minutes, if the execution/unit test got stuck/crash
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # npm command install all required packages 
      - name: npm command
        run: |
          npm install

      # runs gulp command to upload package to roku device and runs all unit tests 
      - name: run gulp command
        run: |
          gulp test --sametab > log.txt 2> log.txt &
          echo "Unit Tests are running"
          PROCESS_ID=$!
          while true
          do
            if cat log.txt | grep "unit_tests_completed"
            then
              echo "Unit Tests are completed"
              break
            fi
          done
          actual=`grep 'RESULT:' log.txt  | tail -1`
          expected="RESULT: Success"
          kill -SIGINT $PROCESS_ID
          cat log.txt
          if [ "$actual" = "$expected" ]; then
              echo "Success"
              exit 0
          else
              echo "Unit tests failed. Please run 'gulp test' on your local branch for more information."
              exit 1
          fi