# This file executes the unit tests when PR is raised against master branch.
# This will be executed in Roku device available in SF office and logs will be captured in machine/server available in SF office.
# Device details can be found here : https://tubitv.atlassian.net/wiki/spaces/IT/pages/edit-v2/2465464321
# Roku IP address and password are taken from .env file from github action runner. If you update it, reboot the machine

name: Execute Unit Tests

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the master branch.
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # name helps to check the status of github action
    name: Execute Unit Tests
    # The type of runner that the job will run. self hosted machine is our own machine setup in SF office and it has dedicated connected roku device.
    runs-on: [self-hosted, roku-build-server, enabled]
    # timeouts after 10 minutes, if the execution/unit test got stuck/crash
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # npm command install all required packages
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      # runs gulp command to upload package to roku device and runs all unit tests
      - name: run gulp command
        run: |
          echo "Unit Tests are running"
          gulp test --sametab > log.txt 2> log.txt
          actual=`grep 'RESULT:' log.txt | tail -1`
          expected="RESULT: Success"
          cat log.txt
          if [ "$actual" = "$expected" ]; then
              echo "Success"
              exit 0
          else
              echo "Unit tests failed. Please run 'gulp test' on your local branch for more information."
              exit 1
          fi
